version: '3.8'

services:

  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_USER: skillnest
      POSTGRES_PASSWORD: skillnest123
      POSTGRES_DB: user_db
    ports:
      - '5436:5432'
    volumes:
      - pgdata-user:/var/lib/postgresql/data

  postgres-follow:
    image: postgres:15
    environment:
      POSTGRES_USER: skillnest
      POSTGRES_PASSWORD: skillnest123
      POSTGRES_DB: follow_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata-follow:/var/lib/postgresql/data

  postgres-connect:
    image: postgres:15
    environment:
      POSTGRES_USER: skillnest
      POSTGRES_PASSWORD: skillnest123
      POSTGRES_DB: connect_db
    ports:
      - '5434:5432'
    volumes:
      - pgdata-connect:/var/lib/postgresql/data

  postgres-chat:
    image: postgres:15
    environment:
      POSTGRES_USER: skillnest
      POSTGRES_PASSWORD: skillnest123
      POSTGRES_DB: chat_db
    ports:
      - '5435:5432'
    volumes:
      - pgdata-chat:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata-user:
  pgdata-follow:
  pgdata-connect:
  pgdata-chat:
  esdata:
